#!/bin/bash
version="0.0.0"
domain="hub.byted.org"
# namespace="base"
namespace="tritonx"
name="mlu-devel-ubuntu20.04"
tag="$version"
image="$domain/$namespace/$name:$tag"
# image="hub.byted.org/base/data.aml.mlu-base:latest"
# base_image="hub.byted.org/base/data.aml.mlu-base:latest"
base_image="cambricon-base/pytorch:v24.12.1-torch2.5.0-torchmlu1.24.1-debian10.11-py310"
http_proxy="http://sys-proxy-rd-relay.byted.org:8118"
proxy_param=" --build-arg ftp_proxy=$http_proxy --build-arg http_proxy=$http_proxy --build-arg https_proxy=$http_proxy "
ASCEND_BASE="/usr/local/Ascend"
APPS_PATH="/opt/apps"
base_image_param=" --build-arg BASE_IMAGE=$base_image --build-arg ASCEND_BASE=$ASCEND_BASE --build-arg APPS_PATH=$APPS_PATH "
